### ISSUE TITLE
Too many levels of symbolic links when running ls -l /proc/sys/fs/binfmt_misc

### ISSUE THREAD

**Issue by hnakamur** [DamionGans/ubuntu-wsl2-systemd-script#15]
After running `bash ubuntu-wsl2-systemd-script.sh` and `wsl.exe -t ${DISTRIBUTION_NAME}` and reopen a terminal for WSL2 VM, I get the following error when I run `ls -l /proc/sys/fs/binfmt_misc`.

```
$ ls -l /proc/sys/fs/binfmt_misc
ls: cannot open directory '/proc/sys/fs/binfmt_misc': Too many levels of symbolic links
```

It would be nice to fix this problem.

**Comment by diddledan** [comment]
I did fix this for myself, but have forgotten what the actual change was in full. I'll try to figure out the exact steps to fix this shortly.

**Comment by jramiresbrito** [comment]
How things are going about this @diddledan ?

**Comment by diddledan** [comment]
@jramiresbrito the code from PR #17 fixes this. Once Damion merges it then it'll be available in this repo. Until then you can use the copy from the `binfmt_misc` branch in my fork at https://github.com/diddledan/ubuntu-wsl2-systemd-script/tree/binfmt_misc

**Comment by DamionGans** [comment]
I have merged the PR :-) enjoy!
