### ISSUE TITLE
Terminal doesn't open with the working directory.

### ISSUE THREAD

**Issue by M-H-Mukit** [DamionGans/ubuntu-wsl2-systemd-script#41]
Before running the script vscode open the working directory path for each terminal. But now it's always loaded with the following path which seems a little bit annoying for me. How can I get the working path if I new terminal each time in vscode?
![image](https://user-images.githubusercontent.com/17855774/92338151-3453ea80-f0d0-11ea-999a-7e1b5e2a0fc0.png)

**Comment by scotty-c** [comment]
This is the same issue raised in #22

**Comment by M-H-Mukit** [comment]
Oh thank you. I am closing this issue and will follow up on #22
