### ISSUE TITLE
Any way to revert running the script?

### ISSUE THREAD

**Issue by abiswas97** [DamionGans/ubuntu-wsl2-systemd-script#59]
I'm new to Linux as a whole, so apologies for bad questions. 

I tried running this through the README (Ubuntu 20.04). Running `gnome-session` does open a desktop environment while using Xlaunch (with -ac argument), but it starts a startup screen that I can't complete as my mouse wont work on it.

Is there anyway I can reverse back to wsl before I ran any of the code?

**Comment by FiestaLake** [comment]
`
#!/bin/bashself_dir=$(pwd)echo "Uninstalling ubuntu-wsl2-systemd-script"sudo rm -rf /usr/sbin/start-systemd-namespacesudo rm -rf /usr/sbin/enter-systemd-namespacesudo rm -rf /etc/sudoers.d/systemd-namespacecd /var/tmpif [ -f "/etc/bash.bashrc" ]; thensudo grep -v "# Start or enter a PID namespace in WSL2source /usr/sbin/start-systemd-namespace" /etc/bash.bashrc &gt; tmpfilesudo mv tmpfile /etc/bash.bashrcficd $self_dir`

**Comment by FiestaLake** [comment]
https://github.com/DamionGans/ubuntu-wsl2-systemd-script/pull/56/commits/c4d3d2e3c11f95a3bd1d1395a299693c96c3e061
