### ISSUE TITLE
Ubuntu shell does not open after executing script

### ISSUE THREAD

**Issue by DamionGans** [DamionGans/ubuntu-wsl2-systemd-script#6]
When executing the script, the Ubuntu (no specific version) app does not open. I don't know why, just yet.

**Comment by paulstelian97** [comment]
Can you manually enter wsl by using `wsl -e /bin/sh` command and try to run bash from this shell?

**Comment by DamionGans** [comment]
My installation is Dutch, but I get the following message (translated)
>wsl -e /bin/sh
An error occurred while mounting one of your file systems. Run 'dmesg' for more information.

**Comment by paulstelian97** [comment]
Well something might be borked in the Ubuntu install. Can you do a "wsl -e mv /etc/wsl.conf /etc/wsl.conf.bak" or something similar? You have an issue in your fstab that prevents the whole bash from starting (not just the systemd namespace -- I don't think sh loads that)

**Comment by DamionGans** [comment]
I discovered docker-desktop was the default WSL environment. I changed it to Ubuntu, but it stil does not start when I click the icon. wsl -e /bin/sh works, though.

**Comment by paulstelian97** [comment]
That's a bit better, so the distro itself isn't broken. We can then as a workaround rename/remove the /usr/sbin/start-systemd-namespace file. Either do it from outside (\\WSL$\Ubuntu\usr\sbin\start-systemd-namespace) or inside (you have /bin/sh as shell; that means no tab completion). You can also edit from that shell (sudo vim) the change in /etc/bash.bashrc to comment out the "source /usr/sbin/start-systemd-namespace" line[s]... for some reason I have multiple instances...

Once you recover the regular Ubuntu environment we can begin doing the actual troubleshooting, so as to prevent this issue from reoccurring.

**Comment by DamionGans** [comment]
I have recovered the ubuntu installation by commenting out the line in /etc/bash.bashrc. What can I do to debug the issue? :-)

**Comment by paulstelian97** [comment]
Well, you can run the line manually and see what errors occur.

**Comment by DamionGans** [comment]
I discovered that for some reason the system is unable to start systemd as a unix daemon.
The line that fails is the following:
```
"$DAEMONIZE" /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target 
```
After running this line (which returns no output), no PID for systemd occurs in the proces list 
```
SYSTEMD_PID="$(ps -efw | grep '/lib/systemd/systemd --system-unit=basic.target$' | grep -v unshare | awk '{print $2}')"
```
And then it fails in the while loop.

**Comment by paulstelian97** [comment]
Can you manually run the line without "$DAEMONIZE" in front of it? That will show all errors on the console. I hope it's not due to some missing program.

**Comment by DamionGans** [comment]
I get no output. I tried using sudo in my current user and using bash --norc

**Comment by paulstelian97** [comment]
I still feel like there is something missing.

Do the files /lib/systemd/systemd, /usr/bin/unshare, $DAEMONIZE (whichever it is set to) exist?

**Comment by DamionGans** [comment]
Okay.. don't laugh...
I forgot to set the default version for WSL to 2....
So the Ubuntu image installed to WSL 1.....
Hahaha
Okay it works now!
Thanks so much for your patience and help.
