### ISSUE TITLE
==> (FIX) Here is a fix for those that has issues starting WSL after using this script <===

### ISSUE THREAD

**Issue by codekuu** [DamionGans/ubuntu-wsl2-systemd-script#96]
1. Open up powershell and write `wsl -d DISTRONAME -u root`
2. Delete `/usr/sbin/start-systemd-namespace` and `/usr/sbin/enter-systemd-namespace` (rm -rf XXX)
3. Edit the file `/etc/bash.bashrc` using your favorite text editor
and comment out `source /usr/sbin/start-systemd-namespace`
It should look something like:
```
# Start or enter a PID namespace in WSL2
# source /usr/sbin/start-systemd-namespace
```

Tada you should now be able to start the WSL again! You can remove those two lines as well if you want.

**Comment by IdaEdz** [comment]
Not strictly running the script, but after following the guide previous to this script; I get the following error trying to start wsl as you discribed.

`>wsl -d DISTRONAME -u root`
`/usr/sbin/enter-systemd-namespace: line 10: /usr/sbin/daemonize: No such file or directory`

**Comment by codekuu** [comment]
@OskyEdz you can open the windows file explorer and go into the WSL disk and do the above instead of using the WSL cli.
![image](https://user-images.githubusercontent.com/47852530/221867052-c3ba43be-8368-44ef-9bec-12919347d786.png)

**Comment by aki-k** [comment]
@codekuu I'm not sure how you think removing this setup is fixing it? There's a real fix in comment https://github.com/DamionGans/ubuntu-wsl2-systemd-script/issues/36#issuecomment-732090101 for Ubuntu-22.04. For Ubuntu-20.04 this script "just works".
